#:schema node_modules/wrangler/config-schema.json
name = "link-rewrite"
main = "src/index.ts"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
JSON_URL = "your json url here"
